# Generated by Django 5.0.6 on 2024-07-13 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='enterprie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise'),
        ),
    ]
