# Generated by Django 5.0.6 on 2024-07-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_taskstatus_employee_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
